<?php
/** @var \Jeland\InfiniteScroll\Block\InfiniteScroll $block */
$enabled = $block->isEnabled();
?>
<?php if ($enabled): ?>
    <div id="infinite-scroll-wrapper" data-next-page-selector=".pages .next a">
        <div id="infinite-loader" class="infinite-loader" style="display:none;">
            <div class="spinner"></div>
        </div>
    </div>
    <script type="text/x-magento-init">
    {
        "#infinite-scroll-wrapper": {
            "Jeland_InfiniteScroll/js/infinite-scroll": {}
        }
    }
    </script>
    <link rel="stylesheet" type="text/css"
          href="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('Jeland_InfiniteScroll::css/infinite-scroll.css'); ?>">
<?php endif; ?>